### PR TITLE
Callback property update include default values

### PR DESCRIPTION
**Pull request by mmoschovas**
## Type of change

- [ ] Bugfix
- [X ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

Update to pass along timedOut and autionId values to callback function

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by aleksatr** [comment]
@mmoschovas can you provide the use-case that requires this update?

**Comment by mmoschovas** [comment]
@aleksatr we have pubs in JAPAC using non GAM adservers. DM was setup to pass back these two fields along with bids, so we need to be able to provide the same values in order to make this backward compatible for them.

**Comment by aleksatr** [comment]
@mmoschovas I'm ok with this change, from what I see `timedOut` and `auctionId` will be available only when the hbSource is holding a new auction, addressing only the last auction that happened. This means that these fields will be `undefined when bids are fetched from cache, and when you have a mix of cached bids + new bids, `auctionId` and `timedOut` will only be related to the portion of bids that were fetched in the auction that just transpired. Is that ok?

**Comment by mmoschovas** [comment]
@aleksatr yep that is all that is needed for this

**Review by aleksatr — APPROVED** [review]

**Comment by naegelin** [comment]
Hey @mmoschovas  - these changes break the object model of PPI . I think we have a proposal that can give you what you need. I will T up a quick call.

**Comment by aleksatr** [comment]
Should be covered by: https://github.com/rubicon-project/PPI/pull/8

**Pull request closed without merging**
